[build]
  # Replace environment variables in HTML files
  command = "find . -name '*.html' -exec sed -i 's/GOOGLE_MAPS_API_KEY/'$GOOGLE_MAPS_API_KEY'/g' {} +"
  
  # Publish directory (root of the repository)
  publish = "."

[build.environment]
  # No environment variables needed

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://maps.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://www.google-analytics.com https://www.googletagmanager.com https://maps.gstatic.com https://*.googleapis.com; connect-src 'self' https://www.google-analytics.com https://analytics.google.com https://region1.analytics.google.com https://www.googletagmanager.com https://maps.googleapis.com; frame-ancestors 'none';"
    
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Don't cache HTML files
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Cache images for 1 month
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  # Cache images for 1 month
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
